###
@hostname = http://134.175.221.21
@port = 8081
@host = {{hostname}}:{{port}}
@basic = Authorization: Basic YWRtaW46cHVibGlj
@node = emqx@127.0.0.1

### 获取API列表
GET {{host}}/api/v4 
{{basic}}

### 获取API列表
GET {{host}}/api/v4/brokers/{{node}} 
{{basic}}

### 获取API列表
GET {{host}}/api/v4/nodes/{{node}} 
{{basic}}

### 获取API列表
GET {{host}}/api/v4/clients
{{basic}}

### 获取API列表
GET {{host}}/api/v4/subscriptions
{{basic}}

### 
POST {{host}}/rules/
{{basic}}